# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'aljrico'

# google-ID: 'UA-112060364-1'

menu:
- {name: 'About Me',     hardlink: true,   url: 'https://aljrico.github.io'}
- {name: 'Tech Stuff',   path: 'menu',     url: 'tech'}
- {name: 'Data Science', path: 'menu',     url: 'data-science'}
- {name: 'Design',       path: 'menu',     url: 'design'}
- {name: 'Tags',         path: '..',       url: 'tags'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'google-plus', link: 'https://plus.google.com/u/0/+AlfredoHernándezC'}
- {icon: 'twitter', link: 'https://twitter.com/aljrico'}
- {icon: 'github', link: 'https://www.github.com/aljrico'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/aljrico'}
- {icon: 'telegram', link: 'https://telegram.me/aljrico'}
# - {icon: 'envelope', link: 'mailto:aldomann.designs@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '👉'
  previous_page: '👈'
  last_page: 'Newest'
  first_page: 'Oldest'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
